CREATE TABLE `ACCOUNT` (
	  `ACCID` int(11) unsigned NOT NULL AUTO_INCREMENT,
	  `ACCOUNT` varchar(32) NOT NULL DEFAULT '',
	  `CHANNEL` varchar(32) NOT NULL DEFAULT '',
	  PRIMARY KEY (`ACCID`),
	  UNIQUE KEY (`ACCOUNT`,`CHANNEL`)
) ENGINE=MyISAM AUTO_INCREMENT=7 DEFAULT CHARSET=latin1;
